# ***House Prices Dataset***

* **Author Name:** Tuhid Khan
* **Email:** tuhidkhan1202@gmail.com



## About the Dataset
This dataset contains house sale prices for King County, Washington, USA (which includes Seattle and surrounding areas). It covers homes sold between **May 2014 and May 2015**. It is widely used for exploratory data analysis (EDA), feature engineering, and regression modeling to evaluate property valuation models.

Primary objectives typically include:
- Performing Exploratory Data Analysis (EDA) on real estate valuation factors.
- Predicting housing prices (`price`) using regression techniques (e.g., Simple, Multiple, Random Forest, or XGBoost).
- Analyzing spatial patterns and feature importance (e.g., impact of waterfront views, square footage, grade, and location).

---

## Dataset Overview & Metadata

- **Dataset URL:** [Kaggle - House Sales in King County, USA](https://www.kaggle.com/datasets/harlfoxem/housesalesprediction)
- **Primary File:** `kc_house_data.csv`
- **File Size:** ~2.52 MB
- **License:** CC0: Public Domain
- **Dataset Shape:** 21,613 Rows × 21 Columns

---

## Data Schema & Variable Description

| Column Name | Data Type | Description |
| :--- | :--- | :--- |
| `id` | String / Object | Unique identification code for each house |
| `date` | String / Datetime | Date the house was sold |
| `price` | Float / Integer | **Target Variable:** Sale price of the home |
| `bedrooms` | Integer | Number of bedrooms |
| `bathrooms` | Float | Number of bathrooms (0.5 accounts for a half-bath) |
| `sqft_living` | Integer | Square footage of interior living space |
| `sqft_lot` | Integer | Square footage of the land lot |
| `floors` | Float | Total floors/levels in the house |
| `waterfront` | Categorical (0/1) | Indicates whether the house has a waterfront view (`1` = Yes, `0` = No) |
| `view` | Integer (0–4) | Rating score for the quality of the property's view |
| `condition` | Integer (1–5) | Rating score for the overall condition of the house |
| `grade` | Integer (1–13) | Overall grade given based on King County grading system |
| `sqft_above` | Integer | Square footage of housing space above ground level |
| `sqft_basement` | Integer | Square footage of housing space in the basement |
| `yr_built` | Integer | Year the house was built |
| `yr_renovated` | Integer | Year of the last renovation (`0` if never renovated) |
| `zipcode` | Integer / String | 5-digit ZIP code area |
| `lat` | Float | Geographic latitude coordinate |
| `long` | Float | Geographic longitude coordinate |
| `sqft_living15` | Integer | Living room area in 2015 (reflecting nearby neighbor averages or updates) |
| `sqft_lot15` | Integer | Lot size area in 2015 (reflecting nearby neighbor averages or updates) |

---

## Variable Classification

- **Target Variable (Continuous):** `price`
- **Continuous Numerical:** `sqft_living`, `sqft_lot`, `sqft_above`, `sqft_basement`, `sqft_living15`, `sqft_lot15`
- **Discrete / Ordinal Numerical:** `bedrooms`, `bathrooms`, `floors`, `view`, `condition`, `grade`, `yr_built`, `yr_renovated`
- **Geographic / Spatial:** `lat`, `long`, `zipcode`
- **Temporal / Datetime:** `date`
- **Binary Categorical:** `waterfront`

In [1]:
# import the required libraries
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("house_price_dataset.csv")

In [3]:
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503


In [4]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='str')

In [5]:
df.shape

(21613, 21)

- Rows = 21613
- Columns = 21

In [6]:
# checking null values
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

- No null values found

In [7]:
# Checking dublicate values
df.duplicated().sum()

np.int64(0)

- No Dublicate values found

# 1. BASIC MATH APPLICATION 
- Calculate percentages (price change, ratios) 
- Work with fractions and proportions from data 

In [8]:
avg_price = df['price'].mean()
df['price_pct_vs_avg'] = ((df['price'] - avg_price) / avg_price) * 100
df[['price', 'price_pct_vs_avg']]

,price,price_pct_vs_avg
0,221900.0,-58.914114
1,538000.0,-0.386630
2,180000.0,-66.672107
3,604000.0,11.833598
4,510000.0,-5.570969
...,...,...
21608,360000.0,-33.344213
21609,400000.0,-25.938015
21610,402101.0,-25.549004
21611,400000.0,-25.938015


In [9]:
# Ratio: living space vs lot size


df['living_to_lot_ratio'] = df['sqft_living'] / df['sqft_lot']
df[['sqft_living', 'sqft_lot', 'living_to_lot_ratio']]

,sqft_living,sqft_lot,living_to_lot_ratio
0,1180,5650,0.208850
1,2570,7242,0.354874
2,770,10000,0.077000
3,1960,5000,0.392000
4,1680,8080,0.207921
...,...,...,...
21608,1530,1131,1.352785
21609,2310,5813,0.397385
21610,1020,1350,0.755556
21611,1600,2388,0.670017


In [10]:
# Proportion: basement space out of total living space

df['basement_proportion'] = df['sqft_basement'] / df['sqft_living']
df[['sqft_basement', 'sqft_living', 'basement_proportion']]

,sqft_basement,sqft_living,basement_proportion
0,0,1180,0.000000
1,400,2570,0.155642
2,0,770,0.000000
3,910,1960,0.464286
4,0,1680,0.000000
...,...,...,...
21608,0,1530,0.000000
21609,0,2310,0.000000
21610,0,1020,0.000000
21611,0,1600,0.000000


In [11]:
# % of homes that are waterfront

waterfront_pct = (df['waterfront'].sum() / len(df)) * 100
waterfront_pct

np.float64(0.7541757275713691)


- price_pct_vs_avg: how far each house's price is from the average price (%)
- living_to_lot_ratio: how much of the lot is used by living space
- basement_proportion: fraction of living space that is basement
- waterfront_pct: % of total homes that are waterfront properties


---
# 2. ALGEBRA (EQUATIONS) 
- Form linear equations using dataset features 
- EXAMPLE: \
Price = a*(sqft) + b*(bedrooms) + c 

In [12]:
# Fit the equation using Linear Regression

from sklearn.linear_model import LinearRegression

X = df[['sqft_living', 'bedrooms']]
y = df['price']

model = LinearRegression()
model.fit(X, y)

a, b = model.coef_
c = model.intercept_

a, b, c

(np.float64(313.94868588015805),
 np.float64(-57066.75892292466),
 np.float64(79469.35907477525))

## Equation
Price = a * sqft_living + b * bedrooms + c

(a, b, c values printed above from the model)

In [13]:
# Use the equation to predict price for a sample house
df['predicted_price'] = a * df['sqft_living'] + b * df['bedrooms'] + c
df[['price', 'predicted_price']]

,price,predicted_price
0,221900.0,278728.531645
1,538000.0,715117.205018
2,180000.0,207076.329357
3,604000.0,466541.747708
4,510000.0,435702.874585
...,...,...
21608,360000.0,388610.571703
21609,400000.0,576423.787766
21610,402101.0,285563.500827
21611,400000.0,410586.979714


In [14]:
# Check how close predictions are (error)
df['prediction_error'] = df['price'] - df['predicted_price']
df[['price', 'predicted_price', 'prediction_error']]

,price,predicted_price,prediction_error
0,221900.0,278728.531645,-56828.531645
1,538000.0,715117.205018,-177117.205018
2,180000.0,207076.329357,-27076.329357
3,604000.0,466541.747708,137458.252292
4,510000.0,435702.874585,74297.125415
...,...,...,...
21608,360000.0,388610.571703,-28610.571703
21609,400000.0,576423.787766,-176423.787766
21610,402101.0,285563.500827,116537.499173
21611,400000.0,410586.979714,-10586.979714



- a: price increase per additional sqft
- b: price increase per additional bedroom
- c: base price when sqft and bedrooms are 0 (intercept)
- prediction_error: difference between actual and predicted price


---
# 3. CREATE VECTORS & MATRICES (NUMPY) 
- Convert selected features into matrix form 
- Create X (features matrix) and y (target vector) 

In [15]:
#Create feature matrix X


import numpy as np

X = df[['sqft_living', 'bedrooms', 'bathrooms']].to_numpy()
X

array([[1.18e+03, 3.00e+00, 1.00e+00],
       [2.57e+03, 3.00e+00, 2.25e+00],
       [7.70e+02, 2.00e+00, 1.00e+00],
       ...,
       [1.02e+03, 2.00e+00, 7.50e-01],
       [1.60e+03, 3.00e+00, 2.50e+00],
       [1.02e+03, 2.00e+00, 7.50e-01]], shape=(21613, 3))

In [16]:
# Create target vector y

y = df['price'].to_numpy()
y

array([221900., 538000., 180000., ..., 402101., 400000., 325000.],
      shape=(21613,))

In [17]:
#Check shapes (rows, columns)
X.shape, y.shape 

((21613, 3), (21613,))


- X: matrix of features (each row = one house, each column = one feature)
- y: vector of target values (price for each house)
- X.shape: (rows, columns) — rows = number of houses, columns = number of features
- y.shape: (rows,) — one price per house


---
# 4. MATRIX OPERATIONS 
- PERFORM: 
- Addition 
- Subtraction 
- Multiplication 

In [18]:
# Create two small sample matrices


A = df[['sqft_living', 'sqft_lot']].to_numpy()[:5]
B = df[['sqft_above', 'sqft_basement']].to_numpy()[:5]
A, B

(array([[ 1180,  5650],
        [ 2570,  7242],
        [  770, 10000],
        [ 1960,  5000],
        [ 1680,  8080]]),
 array([[1180,    0],
        [2170,  400],
        [ 770,    0],
        [1050,  910],
        [1680,    0]]))

In [19]:
# Addition
add_result = A + B
add_result

array([[ 2360,  5650],
       [ 4740,  7642],
       [ 1540, 10000],
       [ 3010,  5910],
       [ 3360,  8080]])

In [20]:
# Subtraction

sub_result = A - B
sub_result

array([[    0,  5650],
       [  400,  6842],
       [    0, 10000],
       [  910,  4090],
       [    0,  8080]])

In [21]:
# Multiplication (element-wise)
mul_result = A * B
mul_result

array([[1392400,       0],
       [5576900, 2896800],
       [ 592900,       0],
       [2058000, 4550000],
       [2822400,       0]])

In [22]:
# Multiplication (matrix/dot product)

dot_result = A @ B.T
dot_result

array([[1392400, 4820600,  908600, 6380500, 1982400],
       [3032600, 8473700, 1978900, 9288720, 4317600],
       [ 908600, 5670900,  592900, 9908500, 1293600],
       [2312800, 6253200, 1509200, 6608000, 3292800],
       [1982400, 6877600, 1293600, 9116800, 2822400]])


- A, B: two matrices, each with 5 rows and 2 columns (taken from the data)
- add_result: A + B → adds matching positions
- sub_result: A - B → subtracts matching positions
- mul_result: A * B → multiplies matching positions (element-wise)
- dot_result: A @ B.T → true matrix multiplication (dot product)


---
# 5. SOLVE SYSTEM OF EQUATIONS 
- SOLVE AX = B USING: 
- Inverse method 
- NumPy functions 

In [23]:
# Create a square matrix A and vector B

A = df[['sqft_living', 'bedrooms']].to_numpy()[:2]
B = df['price'].to_numpy()[:2]
A, B

(array([[1180,    3],
        [2570,    3]]),
 array([221900., 538000.]))

In [24]:
# Solve using Inverse method
A_inv = np.linalg.inv(A)
X_inverse = A_inv @ B
X_inverse


array([   227.41007194, -15481.29496403])

In [25]:
# Solve using NumPy's built-in function
X_solve = np.linalg.solve(A, B)
X_solve

array([   227.41007194, -15481.29496403])


- A: square matrix (2 features, 2 houses) — needs to be square to solve directly
- B: target values (price) for those 2 houses
- X_inverse: solution found by manually inverting A and multiplying by B
- X_solve: solution found using NumPy's solve() function (faster, more stable)
- Both methods should give the same answer


---
# 6. ADVANCED LINEAR ALGEBRA 
- PERFORM: 
- Dot product 
- Matrix multiplication 
- Determinant 
- Inverse of matrix

In [26]:
# Create a sample matrix and vector

A = df[['sqft_living', 'bedrooms']].to_numpy()[:3]
v = df['bathrooms'].to_numpy()[:2]
A, v

(array([[1180,    3],
        [2570,    3],
        [ 770,    2]]),
 array([1.  , 2.25]))

In [27]:
# Dot product
dot_result = A.dot(v)
dot_result

array([1186.75, 2576.75,  774.5 ])

In [28]:
# Matrix multiplication

B = df[['sqft_above', 'sqft_basement']].to_numpy()[:2]
matmul_result = A @ B
matmul_result

array([[1398910,    1200],
       [3039110,    1200],
       [ 912940,     800]])

In [29]:
# Determinant

square_matrix = df[['sqft_living', 'bedrooms']].to_numpy()[:2]
det_result = np.linalg.det(square_matrix)
det_result

np.float64(-4170.000000000001)

In [30]:
# Inverse of matrix
inverse_result = np.linalg.inv(square_matrix)
inverse_result

array([[-0.00071942,  0.00071942],
       [ 0.61630695, -0.28297362]])


- dot_result: dot product of matrix A and vector v (sums products of matching elements)
- matmul_result: matrix multiplication of A and B (combines rows of A with columns of B)
- det_result: determinant of a square matrix — a single number describing the matrix
- inverse_result: inverse of a square matrix — used to "undo" matrix multiplication


---
# 7. EIGENVALUES & EIGENVECTORS 
- Calculate eigenvalues 
- Understand meaning in data 

In [31]:
# Select features and compute covariance matrix

features = df[['sqft_living', 'bedrooms', 'bathrooms']]
cov_matrix = np.cov(features.T)
cov_matrix

array([[8.43533681e+05, 4.92596040e+02, 5.33811988e+02],
       [4.92596040e+02, 8.65015010e-01, 3.69527118e-01],
       [5.33811988e+02, 3.69527118e-01, 5.93151289e-01]])

In [32]:
# Calculate eigenvalues and eigenvectors


eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
eigenvalues, eigenvectors

(array([8.43534307e+05, 5.87414724e-01, 2.45279947e-01]),
 array([[-9.99999629e-01, -6.83831639e-04, -5.23320126e-04],
        [-5.83967471e-04,  9.85188473e-01, -1.71473996e-01],
        [-6.32828300e-04,  1.71473627e-01,  9.85188507e-01]]))


- cov_matrix: shows how features vary together (covariance between sqft_living, bedrooms, bathrooms)
- eigenvalues: show how much "spread" (variance) exists along each eigenvector direction
- eigenvectors: show the direction of that spread
- Largest eigenvalue = direction with most variation in the data (most important pattern)


---
# 8. SVD (SINGULAR VALUE DECOMPOSITION) 
- Apply SVD using NumPy 
- Interpret results 

In [33]:
# Select features and apply SVD

features_matrix = df[['sqft_living', 'bedrooms', 'bathrooms']].to_numpy()[:100]
U, S, VT = np.linalg.svd(features_matrix, full_matrices=False)
U, S, VT

(array([[-0.05227257, -0.10901932,  0.07956068],
        [-0.11384766,  0.06924131, -0.01641083],
        [-0.03411009, -0.08163258, -0.02217812],
        [-0.08682562, -0.12157884, -0.20979431],
        [-0.07442191, -0.0556657 , -0.07562758],
        [-0.2400988 ,  0.35368154, -0.09536436],
        [-0.07597237, -0.05545301, -0.12595568],
        [-0.04695676, -0.13630379, -0.04543883],
        [-0.07885173, -0.02151454,  0.15643426],
        [-0.08372463, -0.03482254, -0.15834662],
        [-0.15770328,  0.20873244,  0.05561818],
        [-0.05138654, -0.02475447,  0.02778971],
        [-0.06334722, -0.072559  ,  0.11159134],
        [-0.06068933, -0.09598475, -0.0605332 ],
        [-0.08018085, -0.21106969,  0.03944539],
        [-0.13068122,  0.02280405, -0.0829529 ],
        [-0.08372461, -0.02503902, -0.04872183],
        [-0.07087805, -0.13494765,  0.1825807 ],
        [-0.05315848, -0.01892082,  0.03291462],
        [-0.05537347, -0.09881043,  0.08852927],
        [-0.07176405

In [34]:
# Check shapes of each part

U.shape, S.shape, VT.shape

((100, 3), (3,), (3, 3))

In [35]:
# Reconstruct the original matrix from U, S, VT

reconstructed = U @ np.diag(S) @ VT
reconstructed



array([[1.180e+03, 3.000e+00, 1.000e+00],
       [2.570e+03, 3.000e+00, 2.250e+00],
       [7.700e+02, 2.000e+00, 1.000e+00],
       [1.960e+03, 4.000e+00, 3.000e+00],
       [1.680e+03, 3.000e+00, 2.000e+00],
       [5.420e+03, 4.000e+00, 4.500e+00],
       [1.715e+03, 3.000e+00, 2.250e+00],
       [1.060e+03, 3.000e+00, 1.500e+00],
       [1.780e+03, 3.000e+00, 1.000e+00],
       [1.890e+03, 3.000e+00, 2.500e+00],
       [3.560e+03, 3.000e+00, 2.500e+00],
       [1.160e+03, 2.000e+00, 1.000e+00],
       [1.430e+03, 3.000e+00, 1.000e+00],
       [1.370e+03, 3.000e+00, 1.750e+00],
       [1.810e+03, 5.000e+00, 2.000e+00],
       [2.950e+03, 4.000e+00, 3.000e+00],
       [1.890e+03, 3.000e+00, 2.000e+00],
       [1.600e+03, 4.000e+00, 1.000e+00],
       [1.200e+03, 2.000e+00, 1.000e+00],
       [1.250e+03, 3.000e+00, 1.000e+00],
       [1.620e+03, 4.000e+00, 1.750e+00],
       [3.050e+03, 3.000e+00, 2.750e+00],
       [2.270e+03, 5.000e+00, 2.500e+00],
       [1.070e+03, 2.000e+00, 1.50


- U: shows relationships between rows (houses)
- S: singular values — importance/strength of each pattern (largest first)
- VT: shows relationships between columns (features)
- reconstructed: rebuilding original data from U, S, VT — should match features_matrix